language: java
jdk: oraclejdk8  
dist: trusty

before_install:
- chmod +x gradlew
- wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

jobs:
  include:
  - stage: ☕ jdk.java.net - OpenJDK - GPL
    env: JDK=8
    script: source install-jdk.sh -F 8
  - # stage: ...
    env: JDK=9
    script: source install-jdk.sh -F 9
    
script: 
 - COVERAGE=0.05 ./gradlew -p ./monolithic/ui check
 - COVERAGE=0.14 ./gradlew -p ./monolithic/service/cart check
 - COVERAGE=0.0 ./gradlew -p ./monolithic/service/user check
 - COVERAGE=0.0 ./gradlew -p ./monolithic/repository/cart check
 - COVERAGE=0.24 ./gradlew -p ./monolithic/repository/order check
 - COVERAGE=0.12 ./gradlew -p ./monolithic/repository/product check
 - COVERAGE=0.24 ./gradlew -p ./monolithic/repository/user check
