language: java
jdk: oraclejdk8
dist: trusty
before_install:
 - chmod +x gradlew
script: 
 ./gradlew test
 ./gradlew jacocoTestReport
 find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'
 COVERAGE=0.30 ./gradlew jacocoTestVerification
deploy:
   provider: s3
   on:
     repo: travis-ci/dpl
