language: java
jdk: oraclejdk8
dist: trusty
before_install:
 - chmod +x gradlew
script: 
 ./gradlew test
 ./gradlew jacocoTestReport
 ./gradlew test jacocoTestCoverageVerification
script:
 - COVERAGE=0.5 ./gradlew -p ./monolithic/ui check
 - COVERAGE=0.5 ./gradlew -p ./monolithic/service/cart check
 - COVERAGE=0.5 ./gradlew -p ./monolithic/service/user check
 - COVERAGE=0.5 ./gradlew -p ./monolithic/repository/order check
 - COVERAGE=0.5 ./gradlew -p ./monolithic/repository/cart check
 - COVERAGE=0.5 ./gradlew -p ./monolithic/repository/product check
 - COVERAGE=0.3 ./gradlew -p ./monolithic/repository/user check
