language: java
jdk: oraclejdk8
dist: trusty
before_install:
 - chmod +x gradlew
script: 
 - COVERAGE=0.06 ./gradlew -p ./monolithic/ui check
 - COVERAGE=0.15 ./gradlew -p ./monolithic/service/cart check
 - COVERAGE=0.0 ./gradlew -p ./monolithic/service/user check
 - COVERAGE=0.0 ./gradlew -p ./monolithic/repository/cart check
 - COVERAGE=0.24 ./gradlew -p ./monolithic/repository/order check
 - COVERAGE=0.13 ./gradlew -p ./monolithic/repository/product check
 - COVERAGE=0.24 ./gradlew -p ./monolithic/repository/user check
